# Debian Buster is the same base as the most recent Raspbian OS
FROM debian:buster

# Specify your e-mail address as the maintainer of the container image
MAINTAINER Tylor Slay "tslay@pdx.edu"

ADD . /app
WORKDIR /app

RUN apt-get update -y && apt-get install -y build-essential git cmake
RUN mkdir build && cmake -S . -B build && cmake --build build

CMD ./build/tests/all-tests
